apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: house-hunt-tls
  namespace: house-hunt
spec:
  secretName: house-hunt-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - househunt.romaine.life
