apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: house-hunt
resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- certificate.yaml
- xlistenerset.yaml
- httproute.yaml
images:
- name: romainecr.azurecr.io/house-hunt
  newName: romainecr.azurecr.io/house-hunt
  newTag: 6b3c8ec
