apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-shared
  namespace: house-hunt
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 5ca5ab55-5b59-48eb-bf5b-3f23bf8011f0
