apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-shared
  namespace: house-hunt
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 44b0ff37-b886-4101-ab19-23388ead9c0b
