name: Deploy Frontend

on:
  push:
    branches: [main]
    paths: ["frontend/**"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Config
        run: |
          export API_URL="https://api.romaine.life/househunt"
          export MAPS_CLIENT_ID="${{ vars.MAPS_CLIENT_ID }}"
          export MICROSOFT_CLIENT_ID="${{ vars.MICROSOFT_CLIENT_ID }}"
          chmod +x ./frontend/generate-config.sh
          ./frontend/generate-config.sh

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
