name: Deploy Frontend

on:
  push:
    branches: [main]
    paths: ["frontend/**"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

env:
  RESOURCE_GROUP_NAME: house-hunt-rg

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://househunt.romaine.life
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Generate Config
        run: |
          export API_URL="https://api.romaine.life/househunt"
          export MAPS_CLIENT_ID=$(az maps account show \
            --name house-hunt-maps \
            --resource-group house-hunt-rg \
            --query "properties.uniqueId" -o tsv)
          chmod +x ./frontend/generate-config.sh
          ./frontend/generate-config.sh

      - name: Add CNAME file
        run: echo "househunt.romaine.life" > ./frontend/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
          cname: househunt.romaine.life
